const en = {
  runPython: "Run Python File",
  runPythonArgs: "Run Python File with Arguments…",
  stopPython: "Stop Python",
  pythonInput: "Python Input",
  pythonEOF: "Send End of Input (EOF)",
  pythonArguments: "Python Arguments",
  pythonArgumentsPrompt: "Arguments separated by spaces; use quotes for values containing spaces.",
  pythonChooseFile: "Open a Python file in the current workspace.",
  pythonRunning: "Python running",
  pythonStopping: "Stopping Python…",
  pythonWaitingInput: "Python: waiting for input",
  pythonFinished: "Python finished (exit code {code}).",
  pythonStopped: "Python stopped.",
  pythonOutputTruncated: "[Earlier output was truncated.]",
  pythonStopBeforeLeaving: "Stop the running Python file before leaving this workspace?",
  pythonStillStopping: "Python is still stopping. Wait for its current operation to return, then try again.",
  pythonInputHint: "Enter a line and press Enter to send.",
  pythonSendInput: "Send",
  pythonSaveFailed: "Save all modified files before running Python.",
  opening: 'Opening Pythona VSCode…',
  failed: 'Unable to open the workbench.',
  preferencesFailed: 'Unable to save workbench settings.',
  themeFailed: 'Unable to load the selected color theme.',
  connectionUnavailable: 'The local workspace connection is unavailable.',
  openFolder: 'Open Folder…',
  folderTitle: 'Open Folder',
  openThis: 'Open This Folder',
  parentFolder: 'Parent Folder',
  recent: 'Recently opened',
  chooseProject: 'Choose a project folder in Documents',
  newFolder: 'New Folder…',
  folderName: 'Folder name',
  invalidName: 'Enter a visible folder name without a slash.',
  closeFolder: 'Close Folder',
  closeWindow: 'Close Window',
  localWorkspace: 'Local workspace',
  saveChanges: 'Save your changes before leaving this workspace?',
  saveAll: 'Save All',
  discard: "Don't Save",
  closed: 'Workspace closed. You can close this window.',
} as const;

type Strings = { [K in keyof typeof en]: string };
const hans: Strings = {
  runPython: "运行 Python 文件",
  runPythonArgs: "带参数运行 Python 文件…",
  stopPython: "停止 Python",
  pythonInput: "Python 输入",
  pythonEOF: "发送输入结束 (EOF)",
  pythonArguments: "Python 参数",
  pythonArgumentsPrompt: "参数以空格分隔；包含空格的参数请加引号。",
  pythonChooseFile: "请打开当前工作区中的 Python 文件。",
  pythonRunning: "Python 正在运行",
  pythonStopping: "正在停止 Python…",
  pythonWaitingInput: "Python：等待输入",
  pythonFinished: "Python 已结束（退出代码 {code}）。",
  pythonStopped: "Python 已停止。",
  pythonOutputTruncated: "[较早的输出已被截断。]",
  pythonStopBeforeLeaving: "离开此工作区前是否停止正在运行的 Python 文件？",
  pythonStillStopping: "Python 仍在停止中。请等待当前操作返回后重试。",
  pythonInputHint: "输入内容后按 Enter 发送。",
  pythonSendInput: "发送",
  pythonSaveFailed: "请先保存所有已修改的文件，再运行 Python。",
  opening: '正在打开 Pythona VSCode…', failed: '无法打开工作台。',
  preferencesFailed: '无法保存工作台设置。',
  themeFailed: '无法加载所选颜色主题。',
  connectionUnavailable: '本地工作区连接不可用。',
  openFolder: '打开文件夹…', folderTitle: '打开文件夹', openThis: '打开此文件夹',
  parentFolder: '上级文件夹', recent: '最近打开', chooseProject: '选择 Documents 中的项目文件夹',
  newFolder: '新建文件夹…', folderName: '文件夹名称', invalidName: '输入不以点开头且不包含斜杠的文件夹名称。',
  closeFolder: '关闭文件夹', closeWindow: '关闭窗口', localWorkspace: '本地工作区',
  saveChanges: '离开此工作区前是否保存更改？', saveAll: '全部保存', discard: '不保存',
  closed: '工作区已关闭。可以关闭此窗口。',
};
const hant: Strings = {
  runPython: "執行 Python 檔案",
  runPythonArgs: "使用引數執行 Python 檔案…",
  stopPython: "停止 Python",
  pythonInput: "Python 輸入",
  pythonEOF: "傳送輸入結束 (EOF)",
  pythonArguments: "Python 引數",
  pythonArgumentsPrompt: "引數以空格分隔；包含空格的引數請加上引號。",
  pythonChooseFile: "請開啟目前工作區中的 Python 檔案。",
  pythonRunning: "Python 正在執行",
  pythonStopping: "正在停止 Python…",
  pythonWaitingInput: "Python：等待輸入",
  pythonFinished: "Python 已結束（結束代碼 {code}）。",
  pythonStopped: "Python 已停止。",
  pythonOutputTruncated: "[較早的輸出已遭截斷。]",
  pythonStopBeforeLeaving: "離開此工作區前是否停止正在執行的 Python 檔案？",
  pythonStillStopping: "Python 仍在停止中。請等候目前的操作返回後再試一次。",
  pythonInputHint: "輸入內容後按 Enter 傳送。",
  pythonSendInput: "傳送",
  pythonSaveFailed: "請先儲存所有已修改的檔案，再執行 Python。",
  opening: '正在開啟 Pythona VSCode…', failed: '無法開啟工作台。',
  preferencesFailed: '無法儲存工作台設定。',
  themeFailed: '無法載入選取的色彩佈景主題。',
  connectionUnavailable: '本機工作區連線無法使用。',
  openFolder: '開啟資料夾…', folderTitle: '開啟資料夾', openThis: '開啟此資料夾',
  parentFolder: '上層資料夾', recent: '最近開啟', chooseProject: '選取 Documents 中的專案資料夾',
  newFolder: '新增資料夾…', folderName: '資料夾名稱', invalidName: '輸入不以點開頭且不包含斜線的資料夾名稱。',
  closeFolder: '關閉資料夾', closeWindow: '關閉視窗', localWorkspace: '本機工作區',
  saveChanges: '離開此工作區前是否儲存變更？', saveAll: '全部儲存', discard: '不要儲存',
  closed: '工作區已關閉。可以關閉此視窗。',
};

const de: Strings = {
  runPython: "Python-Datei ausführen",
  runPythonArgs: "Python-Datei mit Argumenten ausführen…",
  stopPython: "Python beenden",
  pythonInput: "Python-Eingabe",
  pythonEOF: "Eingabeende senden (EOF)",
  pythonArguments: "Python-Argumente",
  pythonArgumentsPrompt: "Argumente durch Leerzeichen trennen; Werte mit Leerzeichen in Anführungszeichen setzen.",
  pythonChooseFile: "Öffne eine Python-Datei im aktuellen Arbeitsbereich.",
  pythonRunning: "Python wird ausgeführt",
  pythonStopping: "Python wird beendet…",
  pythonWaitingInput: "Python: wartet auf Eingabe",
  pythonFinished: "Python beendet (Exitcode {code}).",
  pythonStopped: "Python wurde gestoppt.",
  pythonOutputTruncated: "[Ältere Ausgaben wurden abgeschnitten.]",
  pythonStopBeforeLeaving: "Die laufende Python-Datei vor dem Verlassen dieses Arbeitsbereichs stoppen?",
  pythonStillStopping: "Python wird noch beendet. Warte, bis der aktuelle Vorgang zurückkehrt, und versuche es erneut.",
  pythonInputHint: "Zeile eingeben und mit Enter senden.",
  pythonSendInput: "Senden",
  pythonSaveFailed: "Speichere vor dem Ausführen von Python alle geänderten Dateien.",
  opening: 'Pythona VSCode wird geöffnet…',
  failed: 'Die Workbench konnte nicht geöffnet werden.',
  preferencesFailed: 'Die Workbench-Einstellungen konnten nicht gespeichert werden.',
  themeFailed: 'Das ausgewählte Farbdesign konnte nicht geladen werden.',
  connectionUnavailable: 'Die Verbindung zum lokalen Arbeitsbereich ist nicht verfügbar.',
  openFolder: 'Ordner öffnen…',
  folderTitle: 'Ordner öffnen',
  openThis: 'Diesen Ordner öffnen',
  parentFolder: 'Übergeordneter Ordner',
  recent: 'Zuletzt geöffnet',
  chooseProject: 'Projektordner in Documents auswählen',
  newFolder: 'Neuer Ordner…',
  folderName: 'Ordnername',
  invalidName: 'Gib einen Ordnernamen ohne führenden Punkt und ohne Schrägstrich ein.',
  closeFolder: 'Ordner schließen',
  closeWindow: 'Fenster schließen',
  localWorkspace: 'Lokaler Arbeitsbereich',
  saveChanges: 'Änderungen vor dem Verlassen dieses Arbeitsbereichs speichern?',
  saveAll: 'Alle speichern',
  discard: 'Nicht speichern',
  closed: 'Der Arbeitsbereich wurde geschlossen. Du kannst dieses Fenster schließen.',
};

const fr: Strings = {
  runPython: "Exécuter le fichier Python",
  runPythonArgs: "Exécuter le fichier Python avec des arguments…",
  stopPython: "Arrêter Python",
  pythonInput: "Entrée Python",
  pythonEOF: "Envoyer la fin de saisie (EOF)",
  pythonArguments: "Arguments Python",
  pythonArgumentsPrompt: "Séparez les arguments par des espaces ; utilisez des guillemets pour les valeurs contenant des espaces.",
  pythonChooseFile: "Ouvrez un fichier Python dans l’espace de travail actuel.",
  pythonRunning: "Python en cours d’exécution",
  pythonStopping: "Arrêt de Python…",
  pythonWaitingInput: "Python : en attente de saisie",
  pythonFinished: "Python terminé (code de sortie {code}).",
  pythonStopped: "Python arrêté.",
  pythonOutputTruncated: "[Les sorties précédentes ont été tronquées.]",
  pythonStopBeforeLeaving: "Arrêter le fichier Python en cours avant de quitter cet espace de travail ?",
  pythonStillStopping: "Python est toujours en cours d’arrêt. Attendez la fin de l’opération actuelle, puis réessayez.",
  pythonInputHint: "Saisissez une ligne, puis appuyez sur Entrée.",
  pythonSendInput: "Envoyer",
  pythonSaveFailed: "Enregistrez tous les fichiers modifiés avant d’exécuter Python.",
  opening: 'Ouverture de Pythona VSCode…',
  failed: 'Impossible d’ouvrir le banc d’essai.',
  preferencesFailed: 'Impossible d’enregistrer les paramètres du banc d’essai.',
  themeFailed: 'Impossible de charger le thème de couleur sélectionné.',
  connectionUnavailable: 'La connexion à l’espace de travail local est indisponible.',
  openFolder: 'Ouvrir un dossier…',
  folderTitle: 'Ouvrir un dossier',
  openThis: 'Ouvrir ce dossier',
  parentFolder: 'Dossier parent',
  recent: 'Ouverts récemment',
  chooseProject: 'Choisissez un dossier de projet dans Documents',
  newFolder: 'Nouveau dossier…',
  folderName: 'Nom du dossier',
  invalidName: 'Indiquez un nom de dossier qui ne commence pas par un point et ne contient pas de barre oblique.',
  closeFolder: 'Fermer le dossier',
  closeWindow: 'Fermer la fenêtre',
  localWorkspace: 'Espace de travail local',
  saveChanges: 'Enregistrer les modifications avant de quitter cet espace de travail ?',
  saveAll: 'Tout enregistrer',
  discard: 'Ne pas enregistrer',
  closed: 'L’espace de travail est fermé. Vous pouvez fermer cette fenêtre.',
};

const es: Strings = {
  runPython: "Ejecutar archivo Python",
  runPythonArgs: "Ejecutar archivo Python con argumentos…",
  stopPython: "Detener Python",
  pythonInput: "Entrada de Python",
  pythonEOF: "Enviar fin de entrada (EOF)",
  pythonArguments: "Argumentos de Python",
  pythonArgumentsPrompt: "Separa los argumentos con espacios; usa comillas para los valores que contengan espacios.",
  pythonChooseFile: "Abre un archivo Python en el área de trabajo actual.",
  pythonRunning: "Python en ejecución",
  pythonStopping: "Deteniendo Python…",
  pythonWaitingInput: "Python: esperando entrada",
  pythonFinished: "Python terminó (código de salida {code}).",
  pythonStopped: "Python se detuvo.",
  pythonOutputTruncated: "[Se truncó la salida anterior.]",
  pythonStopBeforeLeaving: "¿Quieres detener el archivo Python antes de salir de esta área de trabajo?",
  pythonStillStopping: "Python todavía se está deteniendo. Espera a que termine la operación actual y vuelve a intentarlo.",
  pythonInputHint: "Escribe una línea y pulsa Enter para enviarla.",
  pythonSendInput: "Enviar",
  pythonSaveFailed: "Guarda todos los archivos modificados antes de ejecutar Python.",
  opening: 'Abriendo Pythona VSCode…',
  failed: 'No se pudo abrir el Workbench.',
  preferencesFailed: 'No se pudo guardar la configuración del Workbench.',
  themeFailed: 'No se pudo cargar el tema de color seleccionado.',
  connectionUnavailable: 'La conexión al área de trabajo local no está disponible.',
  openFolder: 'Abrir carpeta…',
  folderTitle: 'Abrir carpeta',
  openThis: 'Abrir esta carpeta',
  parentFolder: 'Carpeta superior',
  recent: 'Abiertos recientemente',
  chooseProject: 'Elige una carpeta de proyecto en Documents',
  newFolder: 'Nueva carpeta…',
  folderName: 'Nombre de la carpeta',
  invalidName: 'Introduce un nombre de carpeta que no empiece por un punto ni contenga barras.',
  closeFolder: 'Cerrar carpeta',
  closeWindow: 'Cerrar ventana',
  localWorkspace: 'Área de trabajo local',
  saveChanges: '¿Quieres guardar los cambios antes de salir de esta área de trabajo?',
  saveAll: 'Guardar todo',
  discard: 'No guardar',
  closed: 'El área de trabajo está cerrada. Puedes cerrar esta ventana.',
};

const ru: Strings = {
  runPython: "Запустить файл Python",
  runPythonArgs: "Запустить файл Python с аргументами…",
  stopPython: "Остановить Python",
  pythonInput: "Ввод Python",
  pythonEOF: "Отправить конец ввода (EOF)",
  pythonArguments: "Аргументы Python",
  pythonArgumentsPrompt: "Разделяйте аргументы пробелами; значения с пробелами заключайте в кавычки.",
  pythonChooseFile: "Откройте файл Python в текущей рабочей области.",
  pythonRunning: "Python выполняется",
  pythonStopping: "Остановка Python…",
  pythonWaitingInput: "Python: ожидание ввода",
  pythonFinished: "Python завершён (код выхода {code}).",
  pythonStopped: "Python остановлен.",
  pythonOutputTruncated: "[Предыдущий вывод был усечён.]",
  pythonStopBeforeLeaving: "Остановить выполняемый файл Python перед выходом из этой рабочей области?",
  pythonStillStopping: "Python ещё останавливается. Дождитесь завершения текущей операции и повторите попытку.",
  pythonInputHint: "Введите строку и нажмите Enter для отправки.",
  pythonSendInput: "Отправить",
  pythonSaveFailed: "Сохраните все изменённые файлы перед запуском Python.",
  opening: 'Открытие Pythona VSCode…',
  failed: 'Не удалось открыть рабочее место.',
  preferencesFailed: 'Не удалось сохранить параметры рабочего места.',
  themeFailed: 'Не удалось загрузить выбранную цветовую тему.',
  connectionUnavailable: 'Подключение к локальной рабочей области недоступно.',
  openFolder: 'Открыть папку…',
  folderTitle: 'Открыть папку',
  openThis: 'Открыть эту папку',
  parentFolder: 'Родительская папка',
  recent: 'Недавно открытые',
  chooseProject: 'Выберите папку проекта в Documents',
  newFolder: 'Создать папку…',
  folderName: 'Имя папки',
  invalidName: 'Введите имя папки без косой черты и точки в начале.',
  closeFolder: 'Закрыть папку',
  closeWindow: 'Закрыть окно',
  localWorkspace: 'Локальная рабочая область',
  saveChanges: 'Сохранить изменения перед выходом из этой рабочей области?',
  saveAll: 'Сохранить все',
  discard: 'Не сохранять',
  closed: 'Рабочая область закрыта. Это окно можно закрыть.',
};

const ja: Strings = {
  runPython: "Python ファイルを実行",
  runPythonArgs: "引数を指定して Python ファイルを実行…",
  stopPython: "Python を停止",
  pythonInput: "Python 入力",
  pythonEOF: "入力の終わりを送信 (EOF)",
  pythonArguments: "Python の引数",
  pythonArgumentsPrompt: "引数は空白で区切ります。空白を含む値は引用符で囲んでください。",
  pythonChooseFile: "現在のワークスペース内の Python ファイルを開いてください。",
  pythonRunning: "Python 実行中",
  pythonStopping: "Python を停止しています…",
  pythonWaitingInput: "Python: 入力待ち",
  pythonFinished: "Python が終了しました (終了コード {code})。",
  pythonStopped: "Python を停止しました。",
  pythonOutputTruncated: "[以前の出力は切り詰められました。]",
  pythonStopBeforeLeaving: "このワークスペースを離れる前に実行中の Python ファイルを停止しますか？",
  pythonStillStopping: "Python はまだ停止処理中です。現在の処理が戻るのを待ってから再試行してください。",
  pythonInputHint: "入力して Enter キーで送信します。",
  pythonSendInput: "送信",
  pythonSaveFailed: "Python を実行する前に、変更したすべてのファイルを保存してください。",
  opening: 'Pythona VSCode を開いています…',
  failed: 'ワークベンチを開けませんでした。',
  preferencesFailed: 'ワークベンチの設定を保存できませんでした。',
  themeFailed: '選択した配色テーマを読み込めませんでした。',
  connectionUnavailable: 'ローカル ワークスペースに接続できません。',
  openFolder: 'フォルダーを開く…',
  folderTitle: 'フォルダーを開く',
  openThis: 'このフォルダーを開く',
  parentFolder: '親フォルダー',
  recent: '最近開いた項目',
  chooseProject: 'Documents 内のプロジェクトフォルダーを選択',
  newFolder: '新しいフォルダー…',
  folderName: 'フォルダー名',
  invalidName: '先頭にピリオドを付けず、スラッシュを含まないフォルダー名を入力してください。',
  closeFolder: 'フォルダーを閉じる',
  closeWindow: 'ウィンドウを閉じる',
  localWorkspace: 'ローカル ワークスペース',
  saveChanges: 'このワークスペースを離れる前に変更を保存しますか？',
  saveAll: 'すべて保存',
  discard: '保存しない',
  closed: 'ワークスペースを閉じました。このウィンドウを閉じることができます。',
};

const ko: Strings = {
  runPython: "Python 파일 실행",
  runPythonArgs: "인수를 지정하여 Python 파일 실행…",
  stopPython: "Python 중지",
  pythonInput: "Python 입력",
  pythonEOF: "입력 끝 보내기 (EOF)",
  pythonArguments: "Python 인수",
  pythonArgumentsPrompt: "인수는 공백으로 구분하고 공백이 포함된 값은 따옴표로 묶으세요.",
  pythonChooseFile: "현재 작업 영역에서 Python 파일을 여세요.",
  pythonRunning: "Python 실행 중",
  pythonStopping: "Python 중지 중…",
  pythonWaitingInput: "Python: 입력 대기 중",
  pythonFinished: "Python이 종료되었습니다(종료 코드 {code}).",
  pythonStopped: "Python이 중지되었습니다.",
  pythonOutputTruncated: "[이전 출력이 잘렸습니다.]",
  pythonStopBeforeLeaving: "이 작업 영역을 나가기 전에 실행 중인 Python 파일을 중지할까요?",
  pythonStillStopping: "Python이 아직 중지 중입니다. 현재 작업이 반환될 때까지 기다린 후 다시 시도하세요.",
  pythonInputHint: "내용을 입력하고 Enter 키로 전송하세요.",
  pythonSendInput: "전송",
  pythonSaveFailed: "Python을 실행하기 전에 수정한 파일을 모두 저장하세요.",
  opening: 'Pythona VSCode 여는 중…',
  failed: '워크벤치를 열 수 없습니다.',
  preferencesFailed: '워크벤치 설정을 저장할 수 없습니다.',
  themeFailed: '선택한 색 테마를 불러올 수 없습니다.',
  connectionUnavailable: '로컬 작업 영역에 연결할 수 없습니다.',
  openFolder: '폴더 열기…',
  folderTitle: '폴더 열기',
  openThis: '이 폴더 열기',
  parentFolder: '상위 폴더',
  recent: '최근에 연 항목',
  chooseProject: 'Documents에서 프로젝트 폴더 선택',
  newFolder: '새 폴더…',
  folderName: '폴더 이름',
  invalidName: '점으로 시작하지 않고 슬래시가 없는 폴더 이름을 입력하세요.',
  closeFolder: '폴더 닫기',
  closeWindow: '창 닫기',
  localWorkspace: '로컬 작업 영역',
  saveChanges: '이 작업 영역을 나가기 전에 변경 내용을 저장하시겠습니까?',
  saveAll: '모두 저장',
  discard: '저장 안 함',
  closed: '작업 영역이 닫혔습니다. 이 창을 닫아도 됩니다.',
};

const ptBR: Strings = {
  runPython: "Executar Arquivo Python",
  runPythonArgs: "Executar Arquivo Python com Argumentos…",
  stopPython: "Parar Python",
  pythonInput: "Entrada do Python",
  pythonEOF: "Enviar Fim da Entrada (EOF)",
  pythonArguments: "Argumentos do Python",
  pythonArgumentsPrompt: "Separe os argumentos por espaços; use aspas para valores que contenham espaços.",
  pythonChooseFile: "Abra um arquivo Python no workspace atual.",
  pythonRunning: "Python em execução",
  pythonStopping: "Parando Python…",
  pythonWaitingInput: "Python: aguardando entrada",
  pythonFinished: "Python terminou (código de saída {code}).",
  pythonStopped: "Python foi parado.",
  pythonOutputTruncated: "[A saída anterior foi truncada.]",
  pythonStopBeforeLeaving: "Parar o arquivo Python em execução antes de sair deste workspace?",
  pythonStillStopping: "O Python ainda está parando. Aguarde o retorno da operação atual e tente novamente.",
  pythonInputHint: "Digite uma linha e pressione Enter para enviar.",
  pythonSendInput: "Enviar",
  pythonSaveFailed: "Salve todos os arquivos modificados antes de executar Python.",
  opening: 'Abrindo Pythona VSCode…',
  failed: 'Não foi possível abrir o Workbench.',
  preferencesFailed: 'Não foi possível salvar as configurações do Workbench.',
  themeFailed: 'Não foi possível carregar o tema de cores selecionado.',
  connectionUnavailable: 'A conexão com o workspace local não está disponível.',
  openFolder: 'Abrir Pasta…',
  folderTitle: 'Abrir Pasta',
  openThis: 'Abrir Esta Pasta',
  parentFolder: 'Pasta Superior',
  recent: 'Abertos Recentemente',
  chooseProject: 'Escolha uma pasta de projeto em Documents',
  newFolder: 'Nova Pasta…',
  folderName: 'Nome da pasta',
  invalidName: 'Insira um nome de pasta que não comece com ponto nem contenha barras.',
  closeFolder: 'Fechar Pasta',
  closeWindow: 'Fechar Janela',
  localWorkspace: 'Workspace local',
  saveChanges: 'Deseja salvar as alterações antes de sair deste workspace?',
  saveAll: 'Salvar Tudo',
  discard: 'Não Salvar',
  closed: 'O workspace foi fechado. Você pode fechar esta janela.',
};

const translations = { en, de, es, fr, ja, ko, 'pt-BR': ptBR, ru, 'zh-Hans': hans, 'zh-Hant': hant };
export type LanguageCode = keyof typeof translations;

let strings: Strings = en;
export function languageCode(language: string): LanguageCode {
  const normalized = language.trim().replaceAll('_', '-').toLowerCase();
  if (/^zh-(hant|tw|hk|mo)(?:-|$)/.test(normalized)) return 'zh-Hant';
  if (/^zh(?:-|$)/.test(normalized)) return 'zh-Hans';
  const base = normalized.split('-')[0];
  if (base === 'pt') return 'pt-BR';
  return Object.hasOwn(translations, base) ? base as LanguageCode : 'en';
}
export function setLanguage(language: string): void {
  strings = translations[languageCode(language)];
}
export function t(key: keyof Strings): string { return strings[key]; }
